### ISSUE TITLE
PremiumVanish Support

### ISSUE THREAD

**Issue by colterfink** [srnyx/Pl3xMap-SuperVanish#1]
### What and How?

PremiumVanish added as an optional dependency.  

### Why?

PremiumVanish is the premium version of SuperVanish. 

### Are there alternatives?

No.

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

### Anything else

No.

**Comment by srnyx** [comment]
Snapshot version available [here](https://github.com/srnyx/Pl3xMap-SuperVanish/actions/runs/8951370684)
Please let me know if it works so I can release a full update for it :))

**Comment by colterfink** [comment]
No artifacts are available to download from the link provided. I'm away
from my computer for a few more days so can't build myself, if you could
provide a download i'll test it out :)

**Comment by srnyx** [comment]
> No artifacts are available to download from the link provided. I'm away from my computer for a few more days so can't build myself, if you could provide a download i'll test it out :)

Artifact is here: 
![image](https://github.com/srnyx/Pl3xMap-SuperVanish/assets/25808801/b1751b26-2059-4736-aee0-dba21c02ab4b)

**Comment by colterfink** [comment]
Got it thanks! Not being logged into GitHub was the issue :D
Will follow up with if it works!

**Comment by colterfink** [comment]
Just rebooted with the latest version, here's what occurs on startup :)

```
[04:00:34] [Server thread/INFO]: [Pl3xMap-SuperVanish] §dPl3xMap-SuperVanish v1.0.0
[04:00:34] [Server thread/INFO]: [Pl3xMap-SuperVanish] §dBy srnyx
[04:00:34] [Server thread/INFO]: [Pl3xMap-SuperVanish] §5--------------------------
[04:00:34] [Server thread/ERROR]: [Pl3xMap-SuperVanish] SuperVanish/PremiumVanish not found!
```

**Comment by srnyx** [comment]
> Just rebooted with the latest version, here's what occurs on startup :)

I accidentally made it require **both** SuperVanish and PremiumVanish 🤦‍♂️ 
Fixed in [this snapshot](https://github.com/srnyx/Pl3xMap-SuperVanish/actions/runs/8970512664)

**Comment by colterfink** [comment]
Hi, I tried the most recent snapshot and it still didn't work. Thanks for the continued support :)

**Comment by srnyx** [comment]
> Hi, I tried the most recent snapshot and it still didn't work. Thanks for the continued support :)

What errors/warnings?

**Comment by colterfink** [comment]
Hi there, the latest snapshot is actually working sorry for the incorrect info. Thanks!

**Comment by srnyx** [comment]
> Hi there, the latest snapshot is actually working sorry for the incorrect info. Thanks!

Awesome, thank you!
